### ISSUE TITLE
[FR] Some verbs variant are not found

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1104]
- Wiktionary page: https://fr.wiktionary.org/wiki/ferla

I see the one of [Ferla](https://fr.wiktionary.org/wiki/Ferla). I would expect to **also** see the definition of "ferler". 

On the other hand, "ferlas" shows the "ferler" definition, as expected.

**Comment by lasconic** [comment]
I believe "Ferla" is stored as a word and has an entry on the dictionary while "ferla" is only stored as a variant. The search algorithm is not case sensitive and it will find Ferla and stop. 
If we wanted to display both definition, we would need to store Ferla and ferla as two definitions and not using variant. It's a large refactoring... since we use word as a unique key a bit everywhere.

**Comment by BoboTiG** [comment]
Hmm you are right. Let's keep it "simple".
