### ISSUE TITLE
[CA] Add etymology

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#136]
Add etymologies for the catalan locale.

Models:
- [-etimologia-](https://ca.wiktionary.org/wiki/Plantilla:-etimologia-)

**Comment by lasconic** [comment]
Here is an example with -etimologia- https://ca.wiktionary.org/w/index.php?title=dijous&action=raw
I have some code working for it. See PR #175 

But apparently, there is also [etim-lang](https://ca.wiktionary.org/wiki/Plantilla:etim-lang)

**Comment by lasconic** [comment]
I tried to add support for `etim-lang` and I updated the PR. If you agree with the general idea, I could have a look to the SV issue too.

**Comment by lasconic** [comment]
Ok. One to go: -etimologia- New PR here: https://github.com/BoboTiG/ebook-reader-dict/pull/184

-etim-, -etimologia- and etim-lang are used in the head section and without the changes we don't even have the chance to decode the template. It's an ugly hack though... I search for matching templates and add a fake section with this template in order to process it further down the road.
