### ISSUE TITLE
[FR] Adapt "composé de" output

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#1505]
(That template is complex!)

- Wiktionary page: https://fr.wiktionary.org/wiki/Frangistan

Wikicode:
```
{{composé de|فرنگ|ستان|tr1=farang|sens1=Franc|tr2=[[-stan]]|lang=fa}}
```

Output:
```
dérivé de فرنگ, <i>farang</i> («&nbsp;Franc&nbsp;»), avec le suffixe ستان, <i>-stan</i>
```

Expected:
```
composé de فرنگ, <i>farang</i> («&nbsp;Franc&nbsp;») et de ستان, <i>-stan</i>
```

**Comment by lasconic** [comment]
It's not really the template. 

The problem is that the wiktionary template will check the first letter of "tr2", find "[" and output "composé"... 
While our code, doesn't have access to the raw tr2 and so it will find "-", and output "dérivé".

In spirit, our implementation is more correct than wiktionary one since a word + suffix is supposed to use "dérivé"...

So what do we do ?

**Comment by BoboTiG** [comment]
The difference seems harmless, we can live with it I guess. Do you agree?

**Comment by lasconic** [comment]
I agree.
