### ISSUE TITLE
[FR] Redirect conjuged verbs to their infinitive form

### ISSUE THREAD

**Issue by BoboTiG** [BoboTiG/ebook-reader-dict#167]
As [requested](http://www.tiger-222.fr/?d=2020/04/17/22/14/21-un-dictionnaire-alternatif-et-complet-pour-votre-kobo#id2764d8) it would be cool to have conjuged verbs redirecting to their infinitive form instead of nothing.

I already tried some things, but without success. I *think* we could make use of [variants](https://pgaskin.net/dictutil/dicthtml/format.html#html-dicthtml), but it is not clear yet how to do that.

**Comment by lasconic** [comment]
Can you explain what was wrong with variants ?

**Comment by BoboTiG** [comment]
There is nothing wrong with variants, I just can't get to make it work (and I have not really tried though). There may be something to do with the Trie also, but I am lacking of time to have a serious look at it.

**Comment by lasconic** [comment]
Ok. I might have a look tonight or tomorrow.
My first idea would be to detect the verb-flexion like "mangeait" and store them, probably in another json file in a dictionary variants["manger"] = ["mangeait", "mangeais" ...].
They should all go in the Trie indeed and the dictionary can be use to lookup the variants for each infinitive.

**Comment by BoboTiG** [comment]
Yes, it is an idea. Maybe a second JSON file is not needed, just keep all words into one file is OK. But you do as you prefer, we could iterate on it then :)

**Comment by akorx** [comment]
> Ok. I might have a look tonight or tomorrow.
> My first idea would be to detect the verb-flexion like "mangeait" and store them, probably in another json file in a dictionary variants["manger"] = ["mangeait", "mangeais" ...].
> They should all go in the Trie indeed and the dictionary can be used to lookup the variants for each infinitive.

I think that listing all the forms will certainly take a long time, but it seems to be the only solution, but it's really the last big step to make the dictionary complete and make it the most functional.

**Comment by BoboTiG** [comment]
The time is not an issue ;)
I just hope the Kobo will not "freeze" the time to look for a word if there are too many of them.

**Comment by BoboTiG** [comment]
@lasconic have a look at that commit for some details: 7b5c1f594050316225697412c26bbd01e5b94aa1

**Comment by lasconic** [comment]
I see, but then what's the expected behavior ?

* "[silicone](https://fr.wiktionary.org/wiki/silicone)" is a noun but also the verb form in several tenses. I guess we don't want to redirect to "[siliconer](https://fr.wiktionary.org/wiki/silicone)" right ? Do we want to list the definitions of silicone as a verb flexions (impératif, indicatif etc... de siliconer) though ?

* "[colligeait](https://fr.wiktionary.org/wiki/colligeait)" is a pure verb flexion, so it should be redirected to [colliger](https://fr.wiktionary.org/wiki/colliger). It must be added in the `Trie` then and listed as a variant of "colliger" and it should work.

* [peut](https://fr.wiktionary.org/wiki/peux) is also a pure verb flexion of "pouvoir" but its prefix "pe" is different from the prefix of "pouvoir"... So it must be added to the Trie and added in the `pe.html` file but with the definition of "pouvoir", ideally just the verb definition of "pouvoir" since "pouvoir" is also a noun...

**Comment by BoboTiG** [comment]
Let's start the "easy" way and handle "pure" verbs like "pourraient" (when there is no ambiguity). It will be a great first move.

We will handle more complex words later.

Finally, you were right: using a separate JSON would help to manage those words.

WDYF?

**Comment by lasconic** [comment]
Well, I believe it's not the easy way :) but let's see what can be done...

**Comment by lasconic** [comment]
So "pourraient" is not the easy case :) 
The easy case is when the two first letters are not changing between the form and the infinitive. It should work with the PR. I tested the test dict on my kobo and searching for "colligeait" displays "colliger" definition.

**Comment by lasconic** [comment]
I built the full fr dictionary and it seems to work ok on my Kobo. The size increases is around 5MB and it's not noticeably slower.

**Comment by BoboTiG** [comment]
That's awesome!

I will have some time tomorrow for the review, else it will be Monday (sorry for the delay). The first thing I saw and you should have a look, is when a word has several flexions. Try "suis", what will be the result?

Small note: "pouvoir" and "pourraient" both start with the same letters, isn't it the easy case?

**Comment by BoboTiG** [comment]
> I built the full fr dictionary and it seems to work ok on my Kobo. The size increases is around 5MB and it's not noticeably slower.

How many words in total?

**Comment by lasconic** [comment]
`Saved 1,530,014 words into data/fr/data.json`

**Comment by lasconic** [comment]
I added a fix for 3rd group verbs. I will test further with my current book!

**Comment by BoboTiG** [comment]
> I added a fix for 3rd group verbs. I will test further with my current book!

Out of curiosity, which book? :D

**Comment by lasconic** [comment]
Nothing fancy but lot of verbs ;)  "L'illusion" - Maxime Chattam
More fixes for 3rd group verbs.

And I found some issues I didn't fix yet...
* "mirent", "peux" etc... are not supported: first letters are not the same for the conjugation and the infinitive. "mirent" resolves to "[mire](https://fr.wiktionary.org/w/index.php?title=mire)" and not "mirer", and even less "mettre"...
* "minutes" and "courses" are not redirected to "minuter" and "courser" instead of "minute" and "course".

**Comment by BoboTiG** [comment]
> "mirent", "peux" etc... are not supported: first letters are not the same for the conjugation and the infinitive. "mirent" resolves to "[mire](https://fr.wiktionary.org/w/index.php?title=mire)" and not "mirer", and even less "mettre"...
Having 100% precision will be very very hard. If we can target 90% this is way better than any other dictionary ;)
 
> "minutes" and "courses" are not redirected to "minuter" and "courser" instead of "minute" and "course".
Hm for such words we would lose the plural -> singular redirection 🤔

**Comment by lasconic** [comment]
> > "minutes" and "courses" are now redirected to "minuter" and "courser" instead of "minute" and "course".
> 
> Hm for such words we would lose the plural -> singular redirection 🤔

Yes, indeed...

**Comment by BoboTiG** [comment]
I just checked and it works pretty well 👍 

Of course, this is not perfect: "sembla" or "avais" for instance. Overall, his is quite a good feature!

**Comment by lasconic** [comment]
* "sembla" is a bit like minutes or courses, it's also a noun. I just discovered that it's possible to add several entries with the same word in the HTML file and Kobo would display them both ? I could be a solution. I would increase the number of words but it would also fix other issues : Currently a word which is a verb and a noun ("manger"?) has a mix of definition. 

* "avais" is like "peux" or "mirent". I should be added as a word in the `av.html` file with a duplicated definition. Or, depending on your policy on firmware support, it could use the new `prefix_exception` file. See https://github.com/pgaskin/dictutil/issues/14#issuecomment-698456338

**Comment by BoboTiG** [comment]
> "sembla" is a bit like minutes or courses, it's also a noun. I just discovered that it's possible to add several entries with the same word in the HTML file and Kobo should display them both ? I could be a solution. I would increase the number of words but it would also fix other issues : Currently a word which is a verb and a noun ("manger"?) has a mix of definition.

Yes, Kobo will display multiple words, for example "empire" will show "empire" but also "Empire". I never tested with 2 identic entries, that would be interesting :) I do not see the increase as an issue though.
The definition mix is also something cool to have, no need to change that IMO.

> "avais" is like "peux" or "mirent". I should be added as a word in the `av.html` file with a duplicated definition. Or, depending on your policy on firmware support, it could use the new `prefix_exception` file. See [pgaskin/dictutil#14 (comment)](https://github.com/pgaskin/dictutil/issues/14#issuecomment-698456338)

We can start with the duplicated definition, WDYT?

**Comment by akorx** [comment]
> > "mirent", "peux" etc... are not supported: first letters are not the same for the conjugation and the infinitive. "mirent" resolves to "[mire](https://fr.wiktionary.org/w/index.php?title=mire)" and not "mirer", and even less "mettre"...
> 
> Having 100% precision will be very very hard. If we can target 90% this is way better than any other dictionary ;)
> 
> > "minutes" and "courses" are not redirected to "minuter" and "courser" instead of "minute" and "course".
> 
> Hm for such words we would lose the plural -> singular redirection 🤔

The only way to have 100% of success is to recover all the verbs in all their forms; you can't guess via an algorithm that "va" refer to"aller". But where can we find this list?

Another more complex solution, but which would reduce the list on words to wrtie in a file, is to do as the "bescherelle" which is a conjugation dictionary; it does not have the complete list of verbs on all forms, he knows only the exceptions like "va" that comes from "aller" and for the rest of the verbs he only use patterns.
Example:
"shooter", "lancer", "grogner", "esquiver" are modeled on the verb "parler" and will therefore all give identical forms when they are conjugated. 
Conclusion: we would therefore rather have in one corner all the conjugated forms of "{parl}er" (= "{parl}ais", "{parl}as", "{parl}a", etc) and in another a list constructed as follows:
model: "{parl}er" => "{shoot}er", "{lanc}er", "{grogn}er", "{esquiv}er"
So if we look for "shootas", without having clearly written it in a library, we know that the verb "{shoot}er" exists under the form "shootas"because he is based of the model "{par}er" and therefore we can find the correct word "shooter" and found his definition in the dictionary.

Sorry for my bad english, I'm french.

**Comment by lasconic** [comment]
> The only way to have 100% of success is to recover all the verbs in all their forms; you can't guess via an algorithm that "va" refer to"aller". But where can we find this list? the website "https://leconjugueur.lefigaro.fr/" has got it, so it exists somewhere...

We already have this information in wiktionary. The problem is how to store it in the dict file so it works 100% on the time on kobo devices.



> Just a question : with the original dictionary of kobo reader, it's seems to me that it works with conjugated verbs, how does it work?
It doesn't. My understanding is that with these commits, the dict generated by this project is the only freely available french dict for kobo to have some sort of support for a large number of conjugated verb forms (1st, 2nd and 3rd groups if the two first letters are not different between the form and the infinitive, and there is no noun with the same spelling than a form)

> Sorry for my bad english, I'm french.

Aren't we all? ;)

**Comment by akorx** [comment]
Yes I think we are all french ;) 

We will try to continue to speack in english... so what is the problem ? teh serach is to long or the dictionary to big for the storage?

**Comment by BoboTiG** [comment]
> so what is the problem ? the search is to long or the dictionary to big for the storage?

Hm I am not sure I followed everything right, but there is no problem for now 🤔
Everything is OK for now ;)

We are just talking about how to handle corner cases like "je suis" that should return "être".

> how are the search algorithm and the dictionary developed?

In this project, nothing is developped regarding the search algo. We just provide the dictionary and Kobo will work with it. The search algo used is the one from the Kobo ([few details](http://www.tiger-222.fr/?d=2020/04/17/22/14/21-un-dictionnaire-alternatif-et-complet-pour-votre-liseuse#details-techniques) and [other details](https://pgaskin.net/dictutil/dicthtml/)). To be more comfortable with how the dictionary works, you should have a look at "Trie" and read resources I linked in the previous sentence.

**Comment by BoboTiG** [comment]
Nicolas, have a look at [avais](https://fr.wiktionary.org/wiki/avais) with its template:
```
{{fr-verbe-flexion|grp=3|'=oui|ind.i.1s=oui|ind.i.2s=oui|avoir}}
```
It returns "'=oui" but "avoir" is expected.

**Comment by akorx** [comment]
ok, I will try to have a look... the only solution to find "suis" is to use exception. Sometimes the word exist in a verb and a noun like "court" (verb : "courrir", and noun : "court" vs "long"). So you have to present the two définitions why not in two paragraph the first coming from the noun part of the dictionary and the second from the part of conjugated verbs.

**Comment by lasconic** [comment]
> ```
> {{fr-verbe-flexion|grp=3|'=oui|ind.i.1s=oui|ind.i.2s=oui|avoir}}
> ```
> 
> It returns "'=oui" but "avoir" is expected.

Done. See PR #204

**Comment by BoboTiG** [comment]
I close this issue as the primary work has been merged. It will be easier to follow with specific issues (if needed).
