### ISSUE TITLE
Auto-update : Parsing Wiktionary dump fail

### ISSUE THREAD

**Issue by citross** [BoboTiG/ebook-reader-dict#2060]
Hi,

I noticed that newer versions of Wiktionary were not being created, and on looking in to _Actions_, it seems that the _Update dictionaries_ workflow is failing at parsing the data dump. This is occurring across all the languages and has been recurring for the last few weeks.

Additionally, this issue also affects _Daily random word_ & _Update local-specific data_ workflows.

Any idea what might be causing this?

Thank you & Regards!

**Comment by BoboTiG** [comment]
You are right, I didn't notice 😮

**Comment by lasconic** [comment]
Working on it

**Comment by lasconic** [comment]
Wikimedia changed their export schema... that's why --parse fails.

*Daily random word* is a different issue. Sometimes, it's a legit fail, meaning the word is not rendered well. Sometimes it's a cache issue... for a weird reason github actions failed to get the dependencies from the cache but doesn't install dependencies from scratch.

Update-local-specific is still another issue... some scripts are failing because the format of the pages changed.
