### ISSUE TITLE
[FR] Support multiple variants

### ISSUE THREAD

**Issue by patalex74** [BoboTiG/ebook-reader-dict#215]
- Wiktionary page: 
https://fr.wiktionary.org/wiki/venait

Lors de la recherche de "venait" seul la 3ème personne de l'indicatif du verbe "vener" est retourné, alors que dans le wiktionary les 2 sens sont bien indiqués.

Patalex

**Comment by lasconic** [comment]
Indeed, it's a known limitation. Currently we use one of the two verb forms. I thought it was the first one, but apparently it's the second one... 

In order to get both, we could extend the variant in `Word` to an array, but then I'm not sure how Kobo would react if "venait" becomes a variant of both "venir" and "vener"

**Comment by BoboTiG** [comment]
@lasconic could you try multiple variants for that word to check how Kobo will behave? I hope it will display both verbs 🤞 🤞 :)

**Comment by lasconic** [comment]
> @lasconic could you try multiple variants for that word to check how Kobo will behave? I hope it will display both verbs 🤞 🤞 :)

Yes it works. That's the easy case... since "venir" and "vener" both have the same 2 letters prefix...

Then we have the less easy cases...
suis -> être / suivre
ailles -> aller / ailler
