### ISSUE TITLE
[FR] Track wrongly rendered words

### ISSUE THREAD

**Issue by lasconic** [BoboTiG/ebook-reader-dict#722]
This week I ran `fr --check-word-random 50000` every night to find the last remaining bad rendering we might have in the fr locale. I fixed a lot of bugs along the way, filed some issues, and fixed some wiktionary pages. Yesterday I ran with 100000 and got 25 errors ! Only 0.025% !

Here is a list of words still causing problems in a gist. If you see a better way to track this list collaboratively, I'm all ears.

https://gist.github.com/lasconic/cdf7364883886808d8e2d6029c30a544

Tip : On mac, I run the following to update the list, with bad.txt being the list above

```
< bad.txt tr '\n' '\0' | xargs -0 -I{} python -m wikidict fr --check-word {} | tee test_results.txt
```

**Comment by BoboTiG** [comment]
Wow, that's quite a good percent!

**Comment by BoboTiG** [comment]
[ne plus savoir où donner de la tête](https://fr.wiktionary.org/wiki/ne_plus_savoir_o%C3%B9_donner_de_la_t%C3%AAte) is funny, it is actually a limitation of the [composé de](https://fr.wiktionary.org/wiki/Mod%C3%A8le:compos%C3%A9_de) model: it handles only 7 arguments and the word is using 8 :)

So we will keep as-is because our imlementation is the good one :muscle:

**Comment by BoboTiG** [comment]
Should we close the issue? We are pretty good with the French locale :)
